# Generated by Django 4.1.1 on 2022-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
