# Generated by Django 4.1.1 on 2022-09-30 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_project_created_at_alter_project_deadline_and_more'),
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='projecttracker',
            unique_together={('user', 'project')},
        ),
    ]
